### ISSUE TITLE
Support new assignment operators

### ISSUE THREAD

**Issue by qubidt** [mcandre/unmake#122]
Considering 8987722d4366b9951bd856925ba5871567d5a204, I assume that syntax from the upcoming POSIX standard (Issue 8; IEEE 1003.1-202x) is fair game. Given that, these three assignment operators should be supported: `::=`, `+=`, and `?=`

Source: [Austin Group bug tracker; 0000330: In make, add support for assignments "::=", "+=", and "?="](https://www.austingroupbugs.net/view.php?id=330)

Side note: it'd be nice for unmake to detect common non-portable syntax and suggest an alternative, rather than simply erroring out in the parsing stage

**Comment by mcandre** [comment]
Oh, thank you for pointing out the upcoming new assignment syntaxes!

Yes, I plan to take a look at those, get a basic understanding of their semantics, and add them to the grammar.

I agree that the current unmake parse error message format is atrocious. That's due to peg's error handling logic.

Sometimes, peg even gets the expected set wrong! As in the case of an empty rule declaration.

I have another ticket dedicated to improving parse error messages.

Unfortunately, peg's documented `expected!()` macro does not appear to work as described. I tried adding it to the grammar part that deals with UB in empty rule declarations. The macro had no effect on the error message.

**Comment by mcandre** [comment]
Yep, the grammar is easy enough to extend this way. Protecting with some basic unit tests.

Uploading the change soon.

AST changes are important enough to warrant a fresh release. It'll take awhile to generate all the ports for the release, but I'll begin the process for that soon.

**Comment by qubidt** [comment]
I just noticed, from the README:

> unmake assumes the 2008 edition of the POSIX standard, and that make implementations fully comply with the standard.

These operators (and the previous `$^` variable) are not in IEEE 1003.1-2008. So that line should be adjusted, no?

**Comment by mcandre** [comment]
Interesting. Can you please elaborate?

Which of these things are in IEEE 1003.1-2008?

Which are proposed to be in IEEE 1003.1-2008, but not yet accepted?

If these things are accepted but not in IEEE 1003.1-2008, then where indeed are they?

**Comment by qubidt** [comment]
Yeah, the standards docs are referred to by different names which is pretty confusing. To get us on the same page, what I meant by "IEEE 1003.1-2008" can be viewed [here](https://pubs.opengroup.org/onlinepubs/9699919799.2008edition/), and it is what I assumed you were referring to. It is titled:

> POSIX.1-2008 is simultaneously IEEE Std 1003.1™-2008 and The Open Group Technical Standard Base Specifications, Issue 7.

So I think calling it "POSIX.1-2008" is probably the clearest. [This page](https://mywiki.wooledge.org/POSIX) is a good primer on the backgrounds behind the different standards organizations.

Note that POSIX.1-2008 *has already* been superseded by [POSIX.1-2017](https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/). Which is titled:

> The Open Group Base Specifications Issue 7, 2018 edition

And the explanation:

> POSIX.1-2017 is simultaneously IEEE Std 1003.1™-2017 and The Open Group Technical Standard Base Specifications, Issue 7.

So AFAIK, POSIX.1-2017 is just POSIX.1-2008 with some minor corrections ("corrigendums"). The `make` page from both editions:

* [2008](https://pubs.opengroup.org/onlinepubs/9699919799.2008edition/utilities/make.html)
* [2017](https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/utilities/make.html)

There *are* some minor differences/clarifications for this page. I can enumerate them specifically if it'd help 

---

Now, the draft for the *upcoming* edition (POSIX.1-202x) is AKA IEEE P1003.1 Draft; The Open Group Base Specifications, Issue 8 Draft; and ISO/IEC 9945 Draft. It's going to be a *major* revision (Issue 7 -> Issue 8)

*that's* the version of the specification that will have the new syntax (i.e. the `$^` variable and the `::=`, `+=`, and `?=` operators).

So for clarity, in the README, I would refer to the spec as "POSIX.1-2017" rather than "the 2008 edition of the POSIX standard". And I would caveat that syntax from the upcoming edition (tentatively referred to as POSIX.1-202x until it's actually published) is also allowed.

FYI, if you have an account with [The Open Group](https://www.opengroup.org/) (free), (and you've joined The Austin Group project from the portal), you can access the drafts of the next edition as well as the PDF form of the current edition for free on [The Austin Group's webpage](http://www.opengroup.org/austin/). (you'll have to wait a little bit for the credentials to propagate through their system if you just signed up)

**Comment by qubidt** [comment]
To summarize the relationship between the different editions (as far as I can discern):

|   Standard       | The Open Group                                                                                            | IEEE                                                                                | Note                         |
|------------------|-----------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------|------------------------------|
|   POSIX.1-2001   | [Issue 6](https://pubs.opengroup.org/onlinepubs/009604499/)                                               | [IEEE 1003.1-2001](https://standards.ieee.org/ieee/1003.1/1389/)                    |                              |
|                  |                                                                                                           |  + [1003.1-2001/Cor1-2002](https://standards.ieee.org/ieee/1003.1-2001_Cor_1/3332/) | TC1 ("Technical Corrigenda") |
|                  |                                                                                                           |  + [1003.1-2008/Cor2-2016](https://standards.ieee.org/ieee/1003.1-2008_Cor_2/6162/) | TC2                          |
|   POSIX.1-2008   | [Issue 7](https://pubs.opengroup.org/onlinepubs/9699919799.2008edition/)                                  | [IEEE 1003.1-2008](https://standards.ieee.org/ieee/1003.1/4020/)                    |                              |
|                  | [Issue 7, 2013 edition](https://pubs.opengroup.org/onlinepubs/9699919799.2013edition/)                    |  + [1003.1-2008/Cor1-2013](https://standards.ieee.org/ieee/1003.1-2008_Cor_1/5219)  | TC1                          |
|                  | [Issue 7, 2016 edition](https://pubs.opengroup.org/onlinepubs/9699919799.2016edition/)                    |  + [1003.1-2008/Cor2-2016](https://standards.ieee.org/ieee/1003.1-2008_Cor_2/6162)  | TC2                          |
| **POSIX.1-2017** | [Issue 7, 2018 edition](https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/)                    | [IEEE 1003.1-2017](https://standards.ieee.org/ieee/1003.1/7101/)                    | = POSIX.1-2008 + TC1 + TC2   |
|   POSIX.1-202x   | [Issue 8, draft 3](https://www.opengroup.org/austin/restricted/202x-d3/202x_d3.pdf) (pdf, login required) | [IEEE P1003.1-202x/D3](https://standards.ieee.org/ieee/1003.1/7700/)                | 3rd draft (Mar 2023)         |

**Comment by mcandre** [comment]
Thank you for taking the time to spell out so much information, in accessible terms!

No problem. I think I will tentatively support the *draft* "POSIX.1-202x" A.K.A. "IEEE P1003.1-202x/D3" A.K.A. "Open Group Issue 3, draft 3" as the minimum version assumed by unmake.

I am submitting my registration for an account with Open Group. Hopefully they will process the account soon, that I can actually read draft 3.

**Comment by qubidt** [comment]
The signup with Open Group should be automatic, as soon as you click the confirmation email. The issue was my username+password wouldn't work on the Austin Group page until I came back a few hours later (do make sure you join the project first tho)

**Comment by mcandre** [comment]
Excellent.

Where can I find convenient changelog summaries? So that I can catch other discrepancies between what unmake supports (primarily the ol' 2007 release), vs. just the changes made in 2008, 2017, and 2020x draft 3?

**Comment by qubidt** [comment]
For the changes in the 202x draft, (in the PDF) the sections/lines that were changed seem to be highlighted grey.

As for the differences between the Issue 7 editions, you *should* be able see the specific changes in the Corrigenda documents, but I don't think you can avoid paying for those. Personally, I've just been grabbing each edition's html page and `diff`-ing them. 

Hint: it's a *little* easier to read/compare if you pandoc them into markdown first: `curl https://pubs.opengroup.org/onlinepubs/9699919799.2008edition/utilities/make.html
 | pandoc --wrap=none -f html -t commonmark`

**Comment by mcandre** [comment]
It is somewhat inconvenient for a linter to target a spec that is technically hidden by a multi-step, hours long registration process. Yes, it's free, but it's extremely inconvenient for people just trying to get the best use of make.

Particularly awkward that the login form for the Austin mailing list, complains that my account doesn't exist, while the registration form complains that my account already exists. I wish the account system had faster syncing and better overall integration between the different account subsystems.

I can't even read the spec to find out if there is any specific legalese concerning public distribution, until I can access an official public copy of the document (lol).

If the Austin mailing list doesn't let me in over the next few weeks, then one option involves reverting unmake to a pre-202x standard, until the next standard is finalized and published for anonymous access.

**Comment by qubidt** [comment]
Yeah it's a pretty annoying process. But I'd guess the culture/organizing principles are pretty different from what you'd be accustomed to because these are industry standards, not open source projects, and they were started decades ago, before the modern open source/free software community was really a thing.

**Comment by mcandre** [comment]
Retried both the Login and the Register forms today, with the same result as yesterday.

Would you mind emailing me a copy of 202x draft 3 pertaining to `make`?

andrew.pennebaker@gmail.com

**Comment by mcandre** [comment]
Good news.

I thought of resetting my password. That helped me to finally enter the secondary authentication subsystem for the mailing list area.

Waited a couple more hours. And used the new password to grab the PDF. All 4K+ pages of it!

**Comment by qubidt** [comment]
Did you ever receive my email?

**Comment by mcandre** [comment]
I have not :(

However, I am able to access the Issue 8/D3 PDF. I found two minor quirks with the make utility documentation on the section's first page about how the -j flag is described, and the Open Group appears... open to improving that. Looks like we're on our way!
