### ISSUE TITLE
warn on ifdef

### ISSUE THREAD

**Issue by mcandre** [mcandre/unmake#161]
`ifdef` is an extension to POSIX make.

```make
ifdef ...
...
endif
```

is a GNU-ism.

```make
.ifdef ...
...
.endif
```

is a BSD-ism.

**Comment by VladimirMarkelov** [comment]
The same trouble with `ifeq` and `ifneq`. As it must be placed since the very beginning of a line, unmake thinks it is a target name and complains `error: .\Makefile:3:31 found "\n", expected: ":", macro expansion, target`

**Comment by mcandre** [comment]
Indeed.

I do not intend to support handling extended grammars. For now, many such extended syntax will continue to simply trigger a parse error. This is described in broad strokes in the documentation.

Closing for now.
